<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '11.0.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'ABS1',
  'author' => 'Manny Laporte',
  'description' => 'Custom modules for ABS CRM',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'abscrm',
  'published_date' => '2021-08-11 08:16:42',
  'type' => 'module',
  'version' => 1628669802,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'abscrm',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'ABS1_sponsors',
      'class' => 'ABS1_sponsors',
      'path' => 'modules/ABS1_sponsors/ABS1_sponsors.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'ABS1_identifications',
      'class' => 'ABS1_identifications',
      'path' => 'modules/ABS1_identifications/ABS1_identifications.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'ABS1_providers',
      'class' => 'ABS1_providers',
      'path' => 'modules/ABS1_providers/ABS1_providers.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'ABS1_collaborators',
      'class' => 'ABS1_collaborators',
      'path' => 'modules/ABS1_collaborators/ABS1_collaborators.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/abs1_sponsors_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/abs1_identifications_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/abs1_identifications_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/abs1_providers_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/abs1_collaborators_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/abs1_sponsors_opportunitiesMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/abs1_identifications_contactsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/abs1_identifications_accountsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/abs1_providers_opportunitiesMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/abs1_collaborators_opportunitiesMetaData.php',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ABS1_sponsors',
      'to' => 'modules/ABS1_sponsors',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ABS1_identifications',
      'to' => 'modules/ABS1_identifications',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ABS1_providers',
      'to' => 'modules/ABS1_providers',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ABS1_collaborators',
      'to' => 'modules/ABS1_collaborators',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'el_EL',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hr_HR',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'it_it',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lt_LT',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ja_JP',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ko_KR',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lv_LV',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nb_NO',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nl_NL',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pl_PL',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_PT',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ro_RO',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ru_RU',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sv_SE',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'th_TH',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'tr_TR',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_TW',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_CN',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_BR',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ca_ES',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_UK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sr_RS',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sk_SK',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sq_AL',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'et_EE',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_LA',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fi_FI',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ar_SA',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'uk_UA',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'en_us',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'bg_BG',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'cs_CZ',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'da_DK',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'de_DE',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'el_EL',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'es_ES',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'fr_FR',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'he_IL',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'hu_HU',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'hr_HR',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'it_it',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'lt_LT',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'ja_JP',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'ko_KR',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'lv_LV',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'nb_NO',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'nl_NL',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'pl_PL',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'pt_PT',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'ro_RO',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'ru_RU',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'sv_SE',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'th_TH',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'tr_TR',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'zh_TW',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'zh_CN',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'pt_BR',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'ca_ES',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'en_UK',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'sr_RS',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'sk_SK',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'sq_AL',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'et_EE',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'es_LA',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'fi_FI',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'ar_SA',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
      'language' => 'uk_UA',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'en_us',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'bg_BG',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'cs_CZ',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'da_DK',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'de_DE',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'el_EL',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'es_ES',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'fr_FR',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'he_IL',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'hu_HU',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'hr_HR',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'it_it',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'lt_LT',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'ja_JP',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'ko_KR',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'lv_LV',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'nb_NO',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'nl_NL',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'pl_PL',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'pt_PT',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'ro_RO',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'ru_RU',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'sv_SE',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'th_TH',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'tr_TR',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'zh_TW',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'zh_CN',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'pt_BR',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'ca_ES',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'en_UK',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'sr_RS',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'sk_SK',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'sq_AL',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'et_EE',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'es_LA',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'fi_FI',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'ar_SA',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'uk_UA',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'en_us',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'bg_BG',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'cs_CZ',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'da_DK',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'de_DE',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'el_EL',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'es_ES',
    ),
    121 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'fr_FR',
    ),
    122 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'he_IL',
    ),
    123 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'hu_HU',
    ),
    124 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'hr_HR',
    ),
    125 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'it_it',
    ),
    126 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'lt_LT',
    ),
    127 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ja_JP',
    ),
    128 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ko_KR',
    ),
    129 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'lv_LV',
    ),
    130 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'nb_NO',
    ),
    131 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'nl_NL',
    ),
    132 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'pl_PL',
    ),
    133 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'pt_PT',
    ),
    134 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ro_RO',
    ),
    135 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ru_RU',
    ),
    136 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sv_SE',
    ),
    137 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'th_TH',
    ),
    138 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'tr_TR',
    ),
    139 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'zh_TW',
    ),
    140 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'zh_CN',
    ),
    141 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'pt_BR',
    ),
    142 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ca_ES',
    ),
    143 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'en_UK',
    ),
    144 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sr_RS',
    ),
    145 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sk_SK',
    ),
    146 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sq_AL',
    ),
    147 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'et_EE',
    ),
    148 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'es_LA',
    ),
    149 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'fi_FI',
    ),
    150 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ar_SA',
    ),
    151 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'uk_UA',
    ),
    152 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    153 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'bg_BG',
    ),
    154 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'cs_CZ',
    ),
    155 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'da_DK',
    ),
    156 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'de_DE',
    ),
    157 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'el_EL',
    ),
    158 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'es_ES',
    ),
    159 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'fr_FR',
    ),
    160 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'he_IL',
    ),
    161 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'hu_HU',
    ),
    162 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'hr_HR',
    ),
    163 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'it_it',
    ),
    164 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'lt_LT',
    ),
    165 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ja_JP',
    ),
    166 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ko_KR',
    ),
    167 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'lv_LV',
    ),
    168 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'nb_NO',
    ),
    169 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'nl_NL',
    ),
    170 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pl_PL',
    ),
    171 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pt_PT',
    ),
    172 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ro_RO',
    ),
    173 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ru_RU',
    ),
    174 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sv_SE',
    ),
    175 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'th_TH',
    ),
    176 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'tr_TR',
    ),
    177 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'zh_TW',
    ),
    178 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'zh_CN',
    ),
    179 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pt_BR',
    ),
    180 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ca_ES',
    ),
    181 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_UK',
    ),
    182 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sr_RS',
    ),
    183 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sk_SK',
    ),
    184 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sq_AL',
    ),
    185 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'et_EE',
    ),
    186 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'es_LA',
    ),
    187 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'fi_FI',
    ),
    188 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ar_SA',
    ),
    189 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'uk_UA',
    ),
    190 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'en_us',
    ),
    191 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'bg_BG',
    ),
    192 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'cs_CZ',
    ),
    193 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'da_DK',
    ),
    194 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'de_DE',
    ),
    195 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'el_EL',
    ),
    196 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'es_ES',
    ),
    197 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'fr_FR',
    ),
    198 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'he_IL',
    ),
    199 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'hu_HU',
    ),
    200 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'hr_HR',
    ),
    201 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'it_it',
    ),
    202 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'lt_LT',
    ),
    203 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ja_JP',
    ),
    204 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ko_KR',
    ),
    205 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'lv_LV',
    ),
    206 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'nb_NO',
    ),
    207 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'nl_NL',
    ),
    208 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'pl_PL',
    ),
    209 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'pt_PT',
    ),
    210 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ro_RO',
    ),
    211 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ru_RU',
    ),
    212 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sv_SE',
    ),
    213 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'th_TH',
    ),
    214 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'tr_TR',
    ),
    215 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'zh_TW',
    ),
    216 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'zh_CN',
    ),
    217 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'pt_BR',
    ),
    218 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ca_ES',
    ),
    219 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'en_UK',
    ),
    220 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sr_RS',
    ),
    221 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sk_SK',
    ),
    222 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'sq_AL',
    ),
    223 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'et_EE',
    ),
    224 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'es_LA',
    ),
    225 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'fi_FI',
    ),
    226 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'ar_SA',
    ),
    227 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
      'language' => 'uk_UA',
    ),
    228 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    229 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'bg_BG',
    ),
    230 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'cs_CZ',
    ),
    231 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'da_DK',
    ),
    232 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'de_DE',
    ),
    233 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'el_EL',
    ),
    234 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    235 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fr_FR',
    ),
    236 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'he_IL',
    ),
    237 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hu_HU',
    ),
    238 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hr_HR',
    ),
    239 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'it_it',
    ),
    240 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lt_LT',
    ),
    241 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ja_JP',
    ),
    242 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ko_KR',
    ),
    243 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lv_LV',
    ),
    244 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nb_NO',
    ),
    245 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nl_NL',
    ),
    246 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pl_PL',
    ),
    247 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_PT',
    ),
    248 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ro_RO',
    ),
    249 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ru_RU',
    ),
    250 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sv_SE',
    ),
    251 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'th_TH',
    ),
    252 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'tr_TR',
    ),
    253 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_TW',
    ),
    254 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_CN',
    ),
    255 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_BR',
    ),
    256 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ca_ES',
    ),
    257 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_UK',
    ),
    258 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sr_RS',
    ),
    259 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sk_SK',
    ),
    260 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sq_AL',
    ),
    261 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'et_EE',
    ),
    262 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_LA',
    ),
    263 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fi_FI',
    ),
    264 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ar_SA',
    ),
    265 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'uk_UA',
    ),
    266 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'en_us',
    ),
    267 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'bg_BG',
    ),
    268 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'cs_CZ',
    ),
    269 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'da_DK',
    ),
    270 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'de_DE',
    ),
    271 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'el_EL',
    ),
    272 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'es_ES',
    ),
    273 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'fr_FR',
    ),
    274 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'he_IL',
    ),
    275 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'hu_HU',
    ),
    276 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'hr_HR',
    ),
    277 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'it_it',
    ),
    278 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'lt_LT',
    ),
    279 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'ja_JP',
    ),
    280 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'ko_KR',
    ),
    281 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'lv_LV',
    ),
    282 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'nb_NO',
    ),
    283 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'nl_NL',
    ),
    284 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'pl_PL',
    ),
    285 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'pt_PT',
    ),
    286 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'ro_RO',
    ),
    287 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'ru_RU',
    ),
    288 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'sv_SE',
    ),
    289 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'th_TH',
    ),
    290 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'tr_TR',
    ),
    291 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'zh_TW',
    ),
    292 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'zh_CN',
    ),
    293 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'pt_BR',
    ),
    294 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'ca_ES',
    ),
    295 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'en_UK',
    ),
    296 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'sr_RS',
    ),
    297 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'sk_SK',
    ),
    298 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'sq_AL',
    ),
    299 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'et_EE',
    ),
    300 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'es_LA',
    ),
    301 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'fi_FI',
    ),
    302 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'ar_SA',
    ),
    303 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_providers.php',
      'to_module' => 'ABS1_providers',
      'language' => 'uk_UA',
    ),
    304 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    305 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'bg_BG',
    ),
    306 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'cs_CZ',
    ),
    307 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'da_DK',
    ),
    308 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'de_DE',
    ),
    309 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'el_EL',
    ),
    310 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    311 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fr_FR',
    ),
    312 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'he_IL',
    ),
    313 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hu_HU',
    ),
    314 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hr_HR',
    ),
    315 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'it_it',
    ),
    316 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lt_LT',
    ),
    317 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ja_JP',
    ),
    318 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ko_KR',
    ),
    319 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lv_LV',
    ),
    320 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nb_NO',
    ),
    321 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nl_NL',
    ),
    322 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pl_PL',
    ),
    323 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_PT',
    ),
    324 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ro_RO',
    ),
    325 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ru_RU',
    ),
    326 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sv_SE',
    ),
    327 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'th_TH',
    ),
    328 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'tr_TR',
    ),
    329 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_TW',
    ),
    330 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_CN',
    ),
    331 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_BR',
    ),
    332 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ca_ES',
    ),
    333 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_UK',
    ),
    334 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sr_RS',
    ),
    335 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sk_SK',
    ),
    336 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sq_AL',
    ),
    337 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'et_EE',
    ),
    338 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_LA',
    ),
    339 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fi_FI',
    ),
    340 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ar_SA',
    ),
    341 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'uk_UA',
    ),
    342 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'en_us',
    ),
    343 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'bg_BG',
    ),
    344 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'cs_CZ',
    ),
    345 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'da_DK',
    ),
    346 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'de_DE',
    ),
    347 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'el_EL',
    ),
    348 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'es_ES',
    ),
    349 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'fr_FR',
    ),
    350 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'he_IL',
    ),
    351 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'hu_HU',
    ),
    352 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'hr_HR',
    ),
    353 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'it_it',
    ),
    354 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'lt_LT',
    ),
    355 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'ja_JP',
    ),
    356 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'ko_KR',
    ),
    357 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'lv_LV',
    ),
    358 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'nb_NO',
    ),
    359 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'nl_NL',
    ),
    360 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'pl_PL',
    ),
    361 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'pt_PT',
    ),
    362 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'ro_RO',
    ),
    363 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'ru_RU',
    ),
    364 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'sv_SE',
    ),
    365 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'th_TH',
    ),
    366 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'tr_TR',
    ),
    367 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'zh_TW',
    ),
    368 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'zh_CN',
    ),
    369 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'pt_BR',
    ),
    370 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'ca_ES',
    ),
    371 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'en_UK',
    ),
    372 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'sr_RS',
    ),
    373 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'sk_SK',
    ),
    374 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'sq_AL',
    ),
    375 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'et_EE',
    ),
    376 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'es_LA',
    ),
    377 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'fi_FI',
    ),
    378 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'ar_SA',
    ),
    379 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
      'language' => 'uk_UA',
    ),
    380 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'sidecar' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/abs1_sponsors_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/abs1_sponsors_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/abs1_identifications_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/abs1_identifications_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/abs1_identifications_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/abs1_identifications_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/abs1_providers_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/abs1_providers_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/abs1_collaborators_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/abs1_collaborators_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_sponsors_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_sponsors_opportunities_ABS1_sponsors.php',
      'to_module' => 'ABS1_sponsors',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_identifications_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_identifications_contacts_ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_identifications_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_identifications_accounts_ABS1_identifications.php',
      'to_module' => 'ABS1_identifications',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_providers_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_providers_opportunities_ABS1_providers.php',
      'to_module' => 'ABS1_providers',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_collaborators_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/abs1_collaborators_opportunities_ABS1_collaborators.php',
      'to_module' => 'ABS1_collaborators',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/abs1_sponsors_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/abs1_identifications_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/abs1_identifications_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/abs1_providers_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/abs1_collaborators_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);